package pages

const val appealType_dropdown = "text=Выбрать"
const val appealCategory_dropdown = "input[type=text]"
const val appealCategory = "text=АДМИНИСТРАТИВНЫЕ ПРАВОНАРУШЕНИЯ, ОБЩЕСТВЕННАЯ И ДОРОЖНАЯ БЕЗОПАСНОСТЬ"
const val appealSubCategory = "text=Вопросы в сфере оказания государственных услуг"
const val appealForm_dropdown = "text=Форма обращения*Выбрать >> span"
const val appealLanguage_dropdown = "text=Выбрать Государственный Официальный Иной >> div"
const val appealLanguage = "text=Официальный"
const val region_dropdown = "text=Выберите регион"
const val country = "text=Выберите регионРеспублика Казахстан >> i"
const val region = "text=Карагандинская область"
const val adresat_dropdown = "text=Адресат*Выберите адресат >> input[type=text]"
const val adresat = "text=ГУ Аппарат акима Карагандинской области"
const val desciption_textarea = "textarea"
const val appealCharacter_dropdown = "text=Характер обращения*Выбрать >> :nth-match(div, 2)"
const val appealCharacter = "text=Индивидуальное"
const val IIN_input = "[placeholder=ИИН]"
const val surname_input = "[placeholder=Фамилия]"
const val name_input = "[placeholder=Имя]"
const val address = "textarea[name=personFactAddress]"
const val mobilePhone_input = "text=Мобильный телефон СМС об ответе придет на указанный номер >> [placeholder=\"+7 000 000 00 00\"]"
const val send_btn = "text=Отправить"
const val NUTS_btn = "text=НУЦ РК"
const val goToRegistry_btn = "text=Перейти в реестр"
const val appealNumber_text = "#kt_body > ngb-modal-window > div > div > div.modal-body > div > div:nth-child(2)"

